function isInViewport(el){const rect=el.getBoundingClientRect()
let height=rect.height;return(rect.top>=0&&rect.left>=0&&(rect.bottom-height)<=(window.innerHeight||document.documentElement.clientHeight)&&rect.right<=(window.innerWidth||document.documentElement.clientWidth))}
const box=document.querySelector('#home_svg1');if(box){let home_svg1_show=!1;jQuery("#home_svg2").css("visibility","hidden");jQuery("#home_svg1").css("visibility","hidden");document.addEventListener('scroll',function(){if(!home_svg1_show&&isInViewport(box)){let height=box.offsetHeight;let el3=jQuery("<div style='height: "+height+"px'></div>").insertBefore("#home_svg1");jQuery("#home_svg1").css("display","none");jQuery("#home_svg1").css("visibility","visible");const rect=box.getBoundingClientRect();home_svg1_show=!0;setTimeout(function(){el3.remove();jQuery("#home_svg1").css("display","block")},1);jQuery("#home_svg2").css("display","none");setTimeout(function(){jQuery("#home_svg2").css("visibility","visible");jQuery("#home_svg2").css("display","block")},10)}},{passive:!0})}
jQuery(function(){if(jQuery('.we_answer_the_crit_que .ee-toggle-element__controls-wrapper').length){jQuery(".we_answer_the_crit_que .ee-toggle-element__controls-wrapper").append('<div class="prew_dot1_wrap"><div><div class="prew_dot1" style=""></div></div></div>');let prew_dot1=jQuery(".we_answer_the_crit_que .ee-toggle-element__controls-wrapper .prew_dot1");let indicator=jQuery('.we_answer_the_crit_que .ee-toggle-element__indicator');let ul_position=jQuery('.we_answer_the_crit_que .ee-toggle-element__controls-wrapper ul').position();let elems=jQuery(".we_answer_the_crit_que ul li");setTimeout(()=>{let index=0;let w=ul_position.left;elems.each((u)=>{let e=jQuery(elems.get(u));if(u==index){w+=e.outerWidth()/2}else if(u<=index){w+=e.outerWidth()}});prew_dot1.css("left",w)},550);jQuery(".we_answer_the_crit_que ul li").on("click",function(e){var li_width=0;jQuery(".we_answer_the_crit_que ul li").each(function(){li_width+=jQuery(this).outerWidth()});console.log("li_width: ",li_width);jQuery(".prew_dot1_wrap").css("width",li_width+"px");e.stopPropagation();let ul_position=jQuery('.we_answer_the_crit_que .ee-toggle-element__controls-wrapper ul li:first-child').position();let index=elems.index(this);let w=ul_position.left;elems.each((u)=>{let e=jQuery(elems.get(u));if(u==index){w+=e.outerWidth()/2}else if(u<=index){w+=e.outerWidth()}});console.log("ul_position.left",ul_position.left,"w",w);prew_dot1.css("left",w);jQuery("#stickyheader").css("position","inherit");e.preventDefault()})}
if(jQuery("#for-modal-popup").length){let modalClosing=!1;var modal=new tingle.modal({footer:!0,stickyFooter:!1,closeMethods:['overlay','button','escape'],closeLabel:"Close",cssClass:['prewave_custom_modal_wrap','custom-class-2'],onOpen:function(){},onClose:function(){modalClosing=!1},beforeClose:function(){if(!modalClosing){modalClosing=!0;jQuery(".prewave_custom_modal_wrap .tingle-modal-box").addClass("animate__fadeOut");setTimeout(function(){modal.close();jQuery(".prewave_custom_modal_wrap .tingle-modal-box").removeClass("animate__fadeOut")},600);return!1}
return!0}});setTimeout(function(){jQuery("#for-modal-popup article.ee-post .bb-column-link").off().find("*").off();jQuery.getScript("https://www.prewave.com/wp-content/plugins/elementor-extras/assets/lib/video-player/video-player.min.js",function(data,textStatus,jqxhr){});jQuery.getScript("https://www.prewave.com/wp-content/plugins/elementor-extras/assets/lib/jquery-appear/jquery.appear.min.js",function(data,textStatus,jqxhr){});jQuery("#for-modal-popup").on('click','article.ee-post .bb-column-link',function(e){let cl=jQuery(this).closest("article").attr("class");var regex=/post-([0-9]+)/gm
var matches=cl.match(regex);if(matches[0]){let postid=(matches[0].replace("post-",""))
jQuery.get("https://www.prewave.com/wp-admin/admin-ajax.php?action=prewave_get_post&post="+postid,function(content){jQuery.parseHTML(content);modal.setContent(content);modal.open();var element=jQuery('.prewave_custom_modal_wrap .tingle-modal__close').detach();jQuery('.prewave_custom_modal_wrap .tingle-modal-box').append(element);jQuery('#prewave_ajax_load .elementor-element').each(function(){elementorFrontend.elementsHandler.runReadyTrigger(jQuery(this))})})}
e.stopPropagation();e.preventDefault()});jQuery("#for-modal-popup div.ee-toggle-element__controls-wrapper ul > li.ee-toggle-element__controls__item").on("click",function(){jQuery("#for-modal-popup article.ee-post .bb-column-link").off().find("*").off()})},1000)}
let kcounter=jQuery("#10k-counter");function eachMonthOfInterval(dirtyInterval){const interval=dirtyInterval||{}
const startDate=toDate(interval.start)
const endDate=toDate(interval.end)
const endTime=endDate.getTime()
const dates=[]
if(!(startDate.getTime()<=endTime)){throw new RangeError('Invalid interval')}
const currentDate=startDate
currentDate.setHours(0,0,0,0)
currentDate.setDate(1)
while(currentDate.getTime()<=endTime){dates.push(toDate(currentDate))
currentDate.setMonth(currentDate.getMonth()+1)}
return dates}
function toDate(argument){const argStr=Object.prototype.toString.call(argument)
if(argument instanceof Date||(typeof argument==='object'&&argStr==='[object Date]')){return new Date(argument.getTime())}else if(typeof argument==='number'||argStr==='[object Number]'){return new Date(argument)}else{if((typeof argument==='string'||argStr==='[object String]')&&typeof console!=='undefined'){console.warn(new Error().stack)}
return new Date(NaN)}}
function daysInMonth(month,year){return new Date(year,month,0).getDate()}
if(kcounter){let now=new Date();let start_date=new Date(2022,9,20);let start_count=373522;let perday=10000/30;const oneDay=24*60*60*1000;const diffDays=Math.round(Math.abs((start_date-now)/oneDay));let miliseconds_diff=now-start_date;let per_millisecond=perday/oneDay;start_count+=miliseconds_diff*per_millisecond;let this_month_increment=10000/30/1440;setInterval(()=>{},380762)}
var homepageCounterDef=parseInt(custom_params.count_view)+113846;jQuery("#10k-counter > div > div").html(homepageCounterDef)})